import numpy as np
#creating zeros array
zeros_array= np.zeros((3,4),dtype=int)
print('*****zeros-array******')
print(zeros_array)
#creating ones array
ones_array = np.ones((3,4),dtype=int)
print('*****ones-array******')
print(ones_array)
#numpy arange function
numpy_arange= np.arange(10, 30, 5)
print('*****numpy_arange function******')
print(numpy_arange)
#numpy linspace function
print('*****numpy_linspace function******')
numpy_linspace=np.linspace(10, 30, 5)
print(numpy_linspace)
#type of array using numpy and arange function
print('*****1d array******')
a = np.arange(6)
print(a)
print('*****2d array******')
a=np.arange(12).reshape(3,4)
print(a)
print('*****3d array******')
a=np.arange(24).reshape(2,3,4)
print(a)
#apply operation along axis
print('*****operation along axis by mention axis******')
b =np.arange(12).reshape(3,4)
print(b)
print('*****operation along column axis by mention axis= 0 ******')
print(b.sum(axis=0))
print('*****operation along row axis by mention axis= 1 ******')
print(b.sum(axis=1))
c =np.arange(24).reshape(2,3,4)
print('*****operation along column axis by mention axis= 2 ******')
print(c)
print(c.sum(axis=2))
print('*****cumulative sum along axis 1 ******')
print(b.cumsum(axis =1))